### ISSUE TITLE
Archive or find a maintainer for this project

### ISSUE THREAD

**Issue by anachronic** [anachronic/yarn-mode#3]
It's been a long time since I stopped using Emacs daily, and I don't have any more time for this project.

If anyone seeing this wishes to maintain this project please leave a comment and I'll be in touch.

**Comment by mplscorwin** [comment]
I'm trying to promote Emacs as an IDE for our dev-ops initiatives at work and this is a part of my current recommended configuration for react devs.  I'll take it on tho I have no real experience manintaing packages for the community.

**Comment by anachronic** [comment]
That's great! I'll send you an email. Let's talk there

**Comment by anachronic** [comment]
Alright, @mplscorwin is now a maintainer of this project. I really can't spend any time into this, but seeing that he volunteered, I'm gonna leave him as a maintainer.

I'm gonna close, and, of course, not archive this project. :)

**Comment by anachronic** [comment]
Forgot to say, but @mplscorwin could you remove the notice from the README page please?

**Comment by mplscorwin** [comment]
Should be done now.  I'll close this issue once I hear back from travis CI ;)

**Comment by mplscorwin** [comment]
I've reverted stuff.  I will look to apply using the test case your branch fsn @anachronic
